import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
import './styles.mobile.css';
import { api as requestApi, authApi } from './services/api';

const demoUser = { id: 'u1', name: 'Alex Morgan', email: 'alex@orbit.team', initials: 'AM', color: '#e2b6ff' };
const demoMembers = [demoUser, { id: 'u2', name: 'Priya Shah', initials: 'PS', color: '#bdebd6' }, { id: 'u3', name: 'Jordan Lee', initials: 'JL', color: '#ffd7a8' }];
const initialTasks = [
  { id: 't1', title: 'Finalize homepage copy', description: 'Polish the headline and supporting proof points before review.', status: 'todo', priority: 'high', assigneeId: 'u2', dueDate: '2026-08-28', labels: ['Content'], comments: 3 },
  { id: 't2', title: 'Design pricing section', description: 'Explore the comparison table and mobile states.', status: 'todo', priority: 'medium', assigneeId: 'u3', dueDate: '2026-08-30', labels: ['Design'], comments: 5 },
  { id: 't3', title: 'Set up analytics events', description: 'Track signups, navigation and activation moments.', status: 'inprogress', priority: 'medium', assigneeId: 'u1', dueDate: '2026-08-27', labels: ['Development'], comments: 2 },
  { id: 't4', title: 'QA responsive layouts', description: 'Run through the key breakpoints on real devices.', status: 'inprogress', priority: 'low', assigneeId: 'u3', dueDate: '2026-09-02', labels: ['QA'], comments: 1 },
  { id: 't5', title: 'Create launch checklist', description: 'Gather all pre-launch tasks in one place.', status: 'done', priority: 'low', assigneeId: 'u2', dueDate: '2026-08-21', labels: ['Operations'], comments: 4 },
  { id: 't6', title: 'Share staging link', description: 'Send the latest staging build to the wider team.', status: 'done', priority: 'medium', assigneeId: 'u1', dueDate: '2026-08-22', labels: ['Launch'], comments: 2 },
];
const demoComments = { t1: [{ user: demoMembers[2], body: 'The new direction feels clear. I left two small notes in the doc.', createdAt: 'Aug 24, 9:14 AM' }], t3: [{ user: demoMembers[1], body: 'I can help validate the signup event once this is on staging.', createdAt: 'Aug 23, 2:00 PM' }] };

async function api(path, options = {}) { try { return await requestApi(path, options); } catch { return null; } }
const Avatar = ({ user, small = false }) => <span className={`avatar ${small ? 'small' : ''}`} style={{ background: user?.color || '#e2b6ff' }}>{user?.initials || '??'}</span>;

function App() {
  const [user, setUser] = useState(() => JSON.parse(localStorage.getItem('orbit_user') || 'null') || demoUser);
  const [isAuthenticated, setIsAuthenticated] = useState(() => Boolean(localStorage.getItem('orbit_token')));
  const [authMode, setAuthMode] = useState('login');
  const [authForm, setAuthForm] = useState({ name: '', email: '', password: '' });
  const [authError, setAuthError] = useState('');
  const [authLoading, setAuthLoading] = useState(false);
  const [projects, setProjects] = useState([{ id: 'p1', name: 'Launch website' }]);
  const [activeProjectId, setActiveProjectId] = useState('p1');
  const [tasks, setTasks] = useState(initialTasks);
  const [selectedId, setSelectedId] = useState('t1');
  const [activeView, setActiveView] = useState('Board');
  const [notice, setNotice] = useState('');
  const [search, setSearch] = useState('');
  const [filterPriority, setFilterPriority] = useState('all');
  const [sortMode, setSortMode] = useState('default');
  const [isTaskModal, setTaskModal] = useState(false);
  const [isProjectModal, setProjectModal] = useState(false);
  const [comments, setComments] = useState(demoComments);
  const [commentText, setCommentText] = useState('');
  const [projectName, setProjectName] = useState('');
  const [newTask, setNewTask] = useState({ title: '', status: 'todo', priority: 'medium', assigneeId: 'u1' });

  useEffect(() => { if (!isAuthenticated) return undefined; api('/me').then((data) => { if (data?.user) setUser(data.user); else logout(); }); api('/projects').then((data) => data?.length && (setProjects(data), setActiveProjectId(data[0].id))); const socketProtocol = location.protocol === 'https:' ? 'wss:' : 'ws:'; const ws = new WebSocket(`${socketProtocol}//${location.host}/ws`); ws.onmessage = (event) => { const message = JSON.parse(event.data); if (message.type === 'task.updated') setTasks((current) => current.map((task) => task.id === message.task.id ? message.task : task)); if (message.type === 'task.created' && message.task.projectId === activeProjectId) setTasks((current) => current.some((task) => task.id === message.task.id) ? current : [...current, message.task]); }; return () => ws.close(); }, [activeProjectId, isAuthenticated]);
  useEffect(() => { api(`/projects/${activeProjectId}/tasks`).then((data) => data && setTasks(data)); }, [activeProjectId]);
  useEffect(() => { const handleToolbarClick = (event) => { const button = event.target.closest('button'); if (!button) return; const text = button.textContent.trim(); if (button.classList.contains('icon-btn')) setNotice('You are all caught up — no new notifications'); else if (button.classList.contains('help')) setNotice('Help center opened'); else if (text.includes('Filter')) { setFilterPriority((current) => current === 'all' ? 'high' : current === 'high' ? 'medium' : 'all'); setNotice('Filter updated'); } else if (text.includes('Sort')) { setSortMode((current) => current === 'default' ? 'priority' : 'default'); setNotice('Sort order updated'); } else if (text === '•••' || button.classList.contains('card-menu')) setNotice('More actions are available from the task drawer'); else if (text.includes('My tasks')) setNotice('Showing your assigned tasks'); else if (text.includes('Timeline')) setActiveView('Timeline'); else if (text.includes('Inbox')) setNotice('Inbox opened'); else if (text.includes('Members')) setNotice('Members panel opened'); else if (text.includes('Settings')) setNotice('Settings opened'); else if (button.classList.contains('add-label')) setNotice('Labels can be managed from the task drawer'); setTimeout(() => setNotice(''), 2200); }; document.addEventListener('click', handleToolbarClick); return () => document.removeEventListener('click', handleToolbarClick); }, []);
  useEffect(() => { const handleIconClick = (event) => { const icon = event.target.closest('.member-add, .star, .chevron, .workspace-logo, .more'); if (!icon) return; if (icon.classList.contains('member-add')) setProjectModal(true); else if (icon.classList.contains('star')) setNotice('Project added to favorites'); else if (icon.classList.contains('chevron')) setNotice('Workspace switcher opened'); else if (icon.classList.contains('workspace-logo')) setNotice('Workspace overview opened'); else setNotice('Profile menu opened'); setTimeout(() => setNotice(''), 2200); }; document.addEventListener('click', handleIconClick); return () => document.removeEventListener('click', handleIconClick); }, []);
  const filteredTasks = useMemo(() => { const visible = tasks.filter((task) => task.title.toLowerCase().includes(search.toLowerCase()) && (filterPriority === 'all' || task.priority === filterPriority)); return sortMode === 'priority' ? [...visible].sort((a, b) => ({ high: 0, medium: 1, low: 2 }[a.priority] - { high: 0, medium: 1, low: 2 }[b.priority])) : visible; }, [tasks, search, filterPriority, sortMode]);
  const activeProject = projects.find((project) => project.id === activeProjectId) || { name: 'Launch website' };
  const logout = () => { localStorage.removeItem('orbit_token'); localStorage.removeItem('orbit_user'); setIsAuthenticated(false); setAuthForm({ name: '', email: '', password: '' }); setNotice('You have been logged out'); };
  const submitAuth = async (event) => { event.preventDefault(); setAuthLoading(true); setAuthError(''); try { const data = authMode === 'login' ? await authApi.login({ email: authForm.email, password: authForm.password }) : await authApi.register(authForm); localStorage.setItem('orbit_token', data.token); localStorage.setItem('orbit_user', JSON.stringify(data.user)); setUser(data.user); setIsAuthenticated(true); } catch (error) { setAuthError(error.message || 'Unable to authenticate.'); } finally { setAuthLoading(false); } };
  useEffect(() => { const handleProfileClick = (event) => { if (event.target.closest('.profile')) logout(); }; document.addEventListener('click', handleProfileClick); return () => document.removeEventListener('click', handleProfileClick); }, []);
  const selectedTask = selectedId ? tasks.find((task) => task.id === selectedId) : null;
  useEffect(() => { if (selectedTask) api(`/tasks/${selectedTask.id}/comments`).then((data) => data && setComments((current) => ({ ...current, [selectedTask.id]: data }))); }, [selectedId, tasks.length]);
  const updateTask = async (id, patch) => { setTasks((current) => current.map((task) => task.id === id ? { ...task, ...patch } : task)); await api(`/tasks/${id}`, { method: 'PATCH', body: JSON.stringify(patch) }); };
  const addTask = async (event) => { event.preventDefault(); if (!newTask.title.trim()) return; const task = { id: `local-${Date.now()}`, ...newTask, projectId: activeProjectId, description: 'A fresh task for the team.', dueDate: '', labels: ['New'], comments: 0 }; const saved = await api(`/projects/${activeProjectId}/tasks`, { method: 'POST', body: JSON.stringify(newTask) }); setTasks((current) => [...current, saved || task]); setTaskModal(false); setNewTask({ title: '', status: 'todo', priority: 'medium', assigneeId: 'u1' }); setNotice('Task added to your board'); setTimeout(() => setNotice(''), 2500); };
  const addComment = async (event) => { event.preventDefault(); if (!commentText.trim()) return; const comment = { user, body: commentText, createdAt: 'Just now' }; const saved = await api(`/tasks/${selectedTask.id}/comments`, { method: 'POST', body: JSON.stringify({ body: commentText }) }); setComments((current) => ({ ...current, [selectedTask.id]: [...(current[selectedTask.id] || []), saved || comment] })); setTasks((current) => current.map((task) => task.id === selectedTask.id ? { ...task, comments: task.comments + 1 } : task)); setCommentText(''); };
  const createProject = async (event) => { event.preventDefault(); if (!projectName.trim()) return; const project = await api('/projects', { method: 'POST', body: JSON.stringify({ name: projectName, description: 'New team project' }) }); if (project) { setProjects((current) => [...current, project]); setActiveProjectId(project.id); } setProjectModal(false); setNotice(`${projectName} created`); setProjectName(''); setTimeout(() => setNotice(''), 2500); };

  if (!isAuthenticated) return <AuthScreen mode={authMode} setMode={setAuthMode} form={authForm} setForm={setAuthForm} error={authError} loading={authLoading} onSubmit={submitAuth} />;
  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><span className="brand-mark">✦</span><span>orbit</span></div><div className="workspace"><div className="workspace-logo">O</div><div><small>Workspace</small><strong>Acme Studio</strong></div><span className="chevron">⌄</span></div><nav><div className="nav-label">Workspace</div><button className="nav-item active"><span>▦</span> Projects <span className="nav-count">4</span></button><button className="nav-item"><span>▤</span> My tasks</button><button className="nav-item"><span>◷</span> Timeline</button><div className="nav-label space">Manage</div><button className="nav-item"><span>◎</span> Inbox <span className="dot-count">3</span></button><button className="nav-item"><span>♧</span> Members</button></nav><div className="sidebar-bottom"><button className="nav-item"><span>⚙</span> Settings</button><div className="profile"><Avatar user={user} small /><span><strong>{user.name}</strong><small>Free plan</small></span><span className="more">···</span></div></div></aside>
    <main className="main"><header className="topbar"><div className="breadcrumbs"><span>Projects</span><b>/</b><strong>Launch website</strong></div><div className="top-actions"><div className="search"><span>⌕</span><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search anything..." /><kbd>⌘ K</kbd></div><button className="icon-btn" title="Notifications">♧<i></i></button><button className="help">?</button><Avatar user={user} /></div></header><section className="content"><div className="project-head"><div><div className="eyebrow"><span className="status-dot"></span> Active project</div><h1>Launch website <button className="star">☆</button></h1><p>Website refresh · Q3 <span className="inline-sep">·</span> Updated 2h ago</p></div><div className="project-actions"><div className="member-stack">{demoMembers.map((member) => <Avatar key={member.id} user={member} small />)}<span className="member-add">+</span></div><button className="secondary-btn" onClick={() => setProjectModal(true)}>Share</button><button className="primary-btn" onClick={() => setTaskModal(true)}>+ Add task</button></div></div><div className="view-tabs"><div>{['Board', 'List', 'Timeline'].map((view) => <button className={activeView === view ? 'tab active' : 'tab'} onClick={() => setActiveView(view)} key={view}>{view}</button>)}</div><div className="view-options"><button>☷ Filter</button><button>↕ Sort</button><button>•••</button></div></div>{activeView !== 'Board' ? <EmptyView view={activeView} /> : <div className="board">{[['todo', 'To do', 'slate'], ['inprogress', 'In progress', 'violet'], ['done', 'Done', 'green']].map(([status, label, color]) => <div className="column" key={status}><div className="column-head"><span className={`column-icon ${color}`}>{status === 'done' ? '✓' : status === 'inprogress' ? '◒' : '○'}</span><h2>{label}</h2><span className="task-count">{filteredTasks.filter((task) => task.status === status).length}</span><button>•••</button></div><div className="cards">{filteredTasks.filter((task) => task.status === status).map((task) => <TaskCard task={task} members={demoMembers} onClick={() => setSelectedId(task.id)} selected={selectedId === task.id} />)}{status === 'todo' && <button className="add-inline" onClick={() => setTaskModal(true)}>+ Add task</button>}</div></div>)}</div>}</section></main>
    {selectedTask && <TaskDrawer task={selectedTask} user={user} members={demoMembers} comments={comments[selectedTask.id] || []} onClose={() => setSelectedId(null)} onUpdate={updateTask} commentText={commentText} setCommentText={setCommentText} addComment={addComment} />}
    {notice && <div className="toast">✓ {notice}</div>}
    {isTaskModal && <Modal title="Add a task" onClose={() => setTaskModal(false)}><form onSubmit={addTask} className="modal-form"><label>Task name<input autoFocus value={newTask.title} onChange={(e) => setNewTask({ ...newTask, title: e.target.value })} placeholder="e.g. Review final mockups" /></label><div className="form-grid"><label>Status<select value={newTask.status} onChange={(e) => setNewTask({ ...newTask, status: e.target.value })}><option value="todo">To do</option><option value="inprogress">In progress</option><option value="done">Done</option></select></label><label>Priority<select value={newTask.priority} onChange={(e) => setNewTask({ ...newTask, priority: e.target.value })}><option>low</option><option>medium</option><option>high</option></select></label></div><label>Assignee<select value={newTask.assigneeId} onChange={(e) => setNewTask({ ...newTask, assigneeId: e.target.value })}>{demoMembers.map((member) => <option value={member.id} key={member.id}>{member.name}</option>)}</select></label><button className="primary-btn wide">Create task</button></form></Modal>}
    {isProjectModal && <Modal title="Create project" onClose={() => setProjectModal(false)}><form onSubmit={createProject} className="modal-form"><p className="modal-copy">Start a new project workspace for your team.</p><label>Project name<input autoFocus value={projectName} onChange={(event) => setProjectName(event.target.value)} placeholder="e.g. Mobile app launch" /></label><button className="primary-btn wide" type="submit">Create project</button></form></Modal>}
  </div>;
}

function AuthScreen({ mode, setMode, form, setForm, error, loading, onSubmit }) { const isLogin = mode === 'login'; return <div className="auth-screen"><div className="auth-card"><div className="brand auth-brand"><span className="brand-mark">✦</span><span>orbit</span></div><div className="auth-intro"><span className="auth-kicker">TEAM WORKSPACE</span><h1>{isLogin ? 'Welcome back' : 'Create your workspace account'}</h1><p>{isLogin ? 'Sign in to continue to your projects.' : 'Bring your projects, tasks, and team conversations together.'}</p></div><form className="auth-form" onSubmit={onSubmit}>{!isLogin && <label>Full name<input autoFocus value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="Alex Morgan" required /></label>}<label>Email<input autoFocus={isLogin} type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} placeholder="you@company.com" required /></label><label>Password<input type="password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} placeholder="At least 6 characters" minLength="6" required /></label>{error && <div className="auth-error">{error}</div>}<button className="primary-btn auth-submit" disabled={loading}>{loading ? 'Please wait…' : isLogin ? 'Sign in' : 'Create account'}</button></form><div className="auth-switch">{isLogin ? 'New to Orbit?' : 'Already have an account?'} <button onClick={() => setMode(isLogin ? 'register' : 'login')}>{isLogin ? 'Create an account' : 'Sign in'}</button></div><div className="demo-hint">Demo account: <strong>alex@orbit.team</strong> · <strong>password</strong></div></div></div>; }
function TaskCard({ task, members, onClick, selected }) { const assignee = members.find((member) => member.id === task.assigneeId); return <article className={`task-card ${selected ? 'selected' : ''}`} onClick={onClick}><div className="card-top"><span className={`priority ${task.priority}`}>{task.priority === 'high' ? 'High' : task.priority === 'medium' ? 'Medium' : 'Low'}</span><button className="card-menu">•••</button></div><h3>{task.title}</h3><p>{task.description}</p><div className="card-meta"><span className="label-chip">{task.labels?.[0]}</span><span className="comment-count">◌ {task.comments}</span><Avatar user={assignee} small /></div><div className="due"><span>◷</span> {task.dueDate ? new Date(task.dueDate).toLocaleDateString('en-US', { month: 'short', day: 'numeric' }) : 'No due date'}</div></article>; }
function TaskDrawer({ task, user, members, comments, onClose, onUpdate, commentText, setCommentText, addComment }) { const assignee = members.find((member) => member.id === task.assigneeId); return <aside className="drawer"><div className="drawer-head"><span className="drawer-kicker">TASK DETAILS</span><button onClick={onClose}>×</button></div><div className="drawer-body"><div className="drawer-title-row"><span className={`status-pill ${task.status}`}>{task.status === 'done' ? '✓ Done' : task.status === 'inprogress' ? '◒ In progress' : '○ To do'}</span><button className="card-menu">•••</button></div><h2>{task.title}</h2><p className="drawer-description">{task.description}</p><div className="detail-list"><div><span>Assignee</span><button className="assignee-select" onClick={() => onUpdate(task.id, { assigneeId: assignee?.id === 'u1' ? 'u2' : 'u1' })}><Avatar user={assignee} small /> {assignee?.name}⌄</button></div><div><span>Due date</span><strong>◷ {task.dueDate || 'Set a date'}</strong></div><div><span>Priority</span><button className={`priority ${task.priority}`} onClick={() => onUpdate(task.id, { priority: task.priority === 'high' ? 'medium' : task.priority === 'medium' ? 'low' : 'high' })}>{task.priority} priority</button></div><div><span>Labels</span><div className="labels">{task.labels?.map((label) => <span className="label-chip" key={label}>{label}</span>)}<button className="add-label">+</button></div></div></div><div className="activity"><h3>Activity <span>{comments.length + task.comments}</span></h3>{comments.map((comment, index) => <div className="comment" key={index}><Avatar user={comment.user} small /><div><div className="comment-line"><strong>{comment.user?.name || user.name}</strong><time>{comment.createdAt}</time></div><p>{comment.body}</p></div></div>)}<form className="comment-box" onSubmit={addComment}><Avatar user={user} small /><input value={commentText} onChange={(e) => setCommentText(e.target.value)} placeholder="Write a comment..." /><button>↑</button></form></div></div></aside>; }
function Modal({ title, onClose, children }) { return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal" onMouseDown={(e) => e.stopPropagation()}><div className="modal-head"><h2>{title}</h2><button onClick={onClose}>×</button></div>{children}</div></div>; }
function EmptyView({ view }) { return <div className="empty-view"><span>✦</span><h2>{view} view is coming together</h2><p>Use the board view to move quickly, or keep building this space with your team.</p></div>; }

createRoot(document.getElementById('root')).render(<App />);
